# Form implementation generated from reading ui file 'inttostr.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 404)
        MainWindow.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 101))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(87, 227, 137);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 100, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.label_2.setObjectName("label_2")
        self.lineINput = QtWidgets.QLineEdit(self.centralwidget)
        self.lineINput.setGeometry(QtCore.QRect(230, 100, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lineINput.setFont(font)
        self.lineINput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineINput.setObjectName("lineINput")
        self.labeloutput = QtWidgets.QLabel(self.centralwidget)
        self.labeloutput.setGeometry(QtCore.QRect(0, 240, 801, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labeloutput.setFont(font)
        self.labeloutput.setStyleSheet("background-color: rgb(143, 240, 164);")
        self.labeloutput.setText("")
        self.labeloutput.setObjectName("labeloutput")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Convert decimal into string"))
        self.label_2.setText(_translate("MainWindow", "🧮"))
